// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMarketAssistant.StockCardService.Infrastructure.EntityFramework;

#nullable disable

namespace StockCardService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(StockCardDbContext))]
    [Migration("20250624190440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.BondCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MaturityPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("BondCards");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BondId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BondId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.CryptoCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CryptoCards");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.Dividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShareCardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ShareCardId");

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.FinancialReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CAPEX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EBITDA")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FCF")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShareCardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShareCardId");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.Multiplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShareCardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ShareCardId");

                    b.ToTable("Multipliers");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.ShareCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ShareCards");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.Coupon", b =>
                {
                    b.HasOne("StockMarketAssistant.StockCardService.Domain.Entities.BondCard", "Bond")
                        .WithMany("Coupons")
                        .HasForeignKey("BondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bond");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.Dividend", b =>
                {
                    b.HasOne("StockMarketAssistant.StockCardService.Domain.Entities.ShareCard", "ShareCard")
                        .WithMany("Dividends")
                        .HasForeignKey("ShareCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareCard");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.FinancialReport", b =>
                {
                    b.HasOne("StockMarketAssistant.StockCardService.Domain.Entities.ShareCard", "ShareCard")
                        .WithMany("FinancialReports")
                        .HasForeignKey("ShareCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareCard");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.Multiplier", b =>
                {
                    b.HasOne("StockMarketAssistant.StockCardService.Domain.Entities.ShareCard", "ShareCard")
                        .WithMany("Multipliers")
                        .HasForeignKey("ShareCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareCard");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.BondCard", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("StockMarketAssistant.StockCardService.Domain.Entities.ShareCard", b =>
                {
                    b.Navigation("Dividends");

                    b.Navigation("FinancialReports");

                    b.Navigation("Multipliers");
                });
#pragma warning restore 612, 618
        }
    }
}
