// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMarketAssistant.AnalyticsService.Infrastructure.EntityFramework.Context;

#nullable disable

namespace StockMarketAssistant.AnalyticsService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20250814183343_MoveTablesToPublicSchema")]
    partial class MoveTablesToPublicSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMarketAssistant.AnalyticsService.Domain.Entities.AssetRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<int>("BuyTransactionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<int>("SellTransactionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalBuyAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalBuyQuantity")
                        .HasPrecision(18, 0)
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("TotalSellAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalSellQuantity")
                        .HasPrecision(18, 0)
                        .HasColumnType("numeric(18,0)");

                    b.Property<int>("TransactionAmountRank")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionCountRank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StockCardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetType", "PeriodStart", "PeriodEnd", "Context");

                    b.HasIndex("Context", "PortfolioId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("StockCardId", "PeriodStart", "PeriodEnd", "Context", "PortfolioId");

                    b.HasIndex("TransactionAmountRank", "Context", "PeriodStart", "PeriodEnd");

                    b.HasIndex("TransactionCountRank", "Context", "PeriodStart", "PeriodEnd");

                    b.ToTable("asset_ratings", "public");
                });

            modelBuilder.Entity("StockMarketAssistant.AnalyticsService.Domain.Entities.AssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasPrecision(18, 0)
                        .HasColumnType("numeric(18,0)");

                    b.Property<Guid>("StockCardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetType", "TransactionTime");

                    b.HasIndex("PortfolioId", "TransactionTime");

                    b.HasIndex("StockCardId", "TransactionTime");

                    b.HasIndex("TransactionTime");

                    b.HasIndex("TransactionType", "TransactionTime");

                    b.ToTable("asset_transactions", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
