// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMarketAssistant.AnalyticsService.Infrastructure.EntityFramework.Context;

#nullable disable

namespace AnalyticsService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMarketAssistant.AnalyticsService.Domain.Entities.AssetRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer")
                        .HasColumnName("asset_type");

                    b.Property<int>("BuyTransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("buy_transaction_count");

                    b.Property<int>("Context")
                        .HasColumnType("integer")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<int>("SellTransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("sell_transaction_count");

                    b.Property<Guid>("StockCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_card_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<decimal>("TotalBuyAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_buy_amount");

                    b.Property<int>("TotalBuyQuantity")
                        .HasPrecision(18)
                        .HasColumnType("integer")
                        .HasColumnName("total_buy_quantity");

                    b.Property<decimal>("TotalSellAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_sell_amount");

                    b.Property<int>("TotalSellQuantity")
                        .HasPrecision(18)
                        .HasColumnType("integer")
                        .HasColumnName("total_sell_quantity");

                    b.Property<int>("TransactionAmountRank")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_amount_rank");

                    b.Property<int>("TransactionCountRank")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count_rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetType", "PeriodStart", "PeriodEnd", "Context");

                    b.HasIndex("Context", "PortfolioId", "PeriodStart", "PeriodEnd");

                    b.HasIndex("TransactionAmountRank", "Context", "PeriodStart", "PeriodEnd");

                    b.HasIndex("TransactionCountRank", "Context", "PeriodStart", "PeriodEnd");

                    b.HasIndex("StockCardId", "PeriodStart", "PeriodEnd", "Context", "PortfolioId");

                    b.ToTable("asset_ratings", "public");
                });

            modelBuilder.Entity("StockMarketAssistant.AnalyticsService.Domain.Entities.AssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_per_unit");

                    b.Property<int>("Quantity")
                        .HasPrecision(18)
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("StockCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_card_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("TransactionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_time");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TransactionTime");

                    b.HasIndex("AssetType", "TransactionTime");

                    b.HasIndex("PortfolioId", "TransactionTime");

                    b.HasIndex("StockCardId", "TransactionTime");

                    b.HasIndex("TransactionType", "TransactionTime");

                    b.ToTable("asset_transactions", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
