// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMarketAssistant.PortfolioService.Infrastructure.EntityFramework.Context;

#nullable disable

namespace StockMarketAssistant.PortfolioService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251130091337_AddIsPrivateFieldToPortfolioEntity")]
    partial class AddIsPrivateFieldToPortfolioEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("asset_currency");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asset_name");

                    b.Property<string>("AssetTicker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_ticker");

                    b.Property<short>("AssetType")
                        .HasColumnType("smallint")
                        .HasColumnName("asset_type");

                    b.Property<short>("Condition")
                        .HasColumnType("smallint")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<Guid>("StockCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_card_id");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("target_price");

                    b.Property<DateTimeOffset?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_alert");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Alerts_IsActive");

                    b.HasIndex("StockCardId")
                        .HasDatabaseName("IX_Alerts_StockCardId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Alerts_UserId");

                    b.HasIndex("AssetType", "AssetTicker")
                        .HasDatabaseName("IX_Alerts_AssetType_Ticker");

                    b.HasIndex("IsActive", "AssetType", "AssetTicker")
                        .HasDatabaseName("IX_Alerts_Active_AssetType_Ticker");

                    b.ToTable("alert", (string)null);
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("Topic")
                        .HasDatabaseName("IX_OutboxMessages_Topic");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("IX_OutboxMessages_Processed_Created");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolio");

                    b.ToTable("portfolio", (string)null);
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.PortfolioAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AssetType")
                        .HasColumnType("smallint")
                        .HasColumnName("asset_type");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("StockCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_card_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_asset");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_portfolio_asset_portfolio_id");

                    b.ToTable("portfolio_asset", (string)null);
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.PortfolioAssetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<Guid>("PortfolioAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_asset_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_unit");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_asset_transaction");

                    b.HasIndex("PortfolioAssetId")
                        .HasDatabaseName("ix_portfolio_asset_transaction_portfolio_asset_id");

                    b.ToTable("portfolio_asset_transaction", (string)null);
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.PortfolioAsset", b =>
                {
                    b.HasOne("StockMarketAssistant.PortfolioService.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Assets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_asset_portfolio_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.PortfolioAssetTransaction", b =>
                {
                    b.HasOne("StockMarketAssistant.PortfolioService.Domain.Entities.PortfolioAsset", "PortfolioAsset")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_asset_transaction_portfolio_asset_portfolio_asset");

                    b.Navigation("PortfolioAsset");
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("StockMarketAssistant.PortfolioService.Domain.Entities.PortfolioAsset", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
